# Generated by Django 5.2 on 2025-04-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_clothingitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='clothing_item', through='main.ClothingItemSize', to='main.size'),
        ),
    ]
